### ISSUE TITLE
Fail when creating a table

### ISSUE THREAD

**Issue by AdrianBZG** [Ensembl/WiggleDB#2]
When using wiggleDB.py --db database.sqlite3 --load datasets.tsv, it gives a error in the CREATE TABLE query:

![image](https://user-images.githubusercontent.com/8275330/36273685-9eaa272c-1285-11e8-8bef-b7c729347097.png)

What's happening: because in the code there's a join using ",\n", the last table column has a , just before the ending ), giving a SQL syntax error.

I'm working on this.

**Comment by AdrianBZG** [comment]
Please check [pull request 3](https://github.com/Ensembl/WiggleDB/pull/3).

**Comment by dzerbino** [comment]
All good, thanks!
